package SeleniumTests;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class DemoSalesforce {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		

		
		System.setProperty("webdriver.chrome.driver","D:\\MyJavaLearning\\Drivers\\chromedriver.exe"); //Use double '\\' for escape sequence
		WebDriver driver = new ChromeDriver();
		driver.get("https://google.com");  //Get the URL in the browser
		System.out.println(driver.getTitle());
	
		driver.get("https://login.salesforce.com/");
		driver.findElement(By.id("username")).sendKeys("sudeshdeulkar95@gmail.com"); 
		driver.findElement(By.name("pw")).sendKeys("password");
		//driver.findElement(By.className("button r4 wide primary")).click(); //Error
		driver.findElement(By.xpath("//*[@id='Login']")).click(); // Xpath generated by tool
		//System.out.println(driver.findElement(By.cssSelector("div#error.loginError")).getText());
		driver.quit();		

	}

}